# Site settings
title: ChriZ - 产品经理|创作|生活|学习|爱
description: "ChriZ - 进击的产品经理|创作|生活|学习|爱"
url: "http://chriz.vip"
author:
  name: "ChriZ"
  email: "gorillazchris@gmail.com"
  url: "http://chriz.vip"
# Added by ChriZ
future: true
timezone: nil

# Build settings
baseurl: "" # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"
motto: "2016"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
